Russian Checkers
AbdullinAM/programming-task3-2022 pull request #2
Opened 2022-05-08 11:01 UTC by MikleAKA

2022-05-12 13:48 UTC, AbdullinAM commented
github action падает

2022-05-12 14:01 UTC, AbdullinAM requested changes

2022-05-12 14:01 UTC, AbdullinAM commented on src/main/kotlin/tornadofx/CheckersApp.kt
> +package tornadofx
Хотелось бы иметь более user friendly интерфейс: чтобы показывались возможные на данный момент ходы. Ну и не очень удобно что шашка закрывает собой черный цвет самой клетки (возможно это так только в моей реализации)

2022-05-12 14:01 UTC, AbdullinAM commented on src/main/kotlin/core/Cell.kt
> +class Cell(val x: Int, val y: Int) {
можно сделать data class

2022-05-12 14:01 UTC, AbdullinAM commented on src/main/kotlin/core/Board.kt
> +    private val checkers: MutableMap<Cell, Checker?> = mutableMapOf()
Почему значение nullable?

2022-05-12 14:01 UTC, AbdullinAM commented on src/main/kotlin/core/Checker.kt
> +    private var mainBoard: Board? = null
Почему это nullable var? Почему это не сделать параметром конструктора?

2022-05-12 14:01 UTC, AbdullinAM commented on src/main/kotlin/core/Checker.kt
> +    private var tempBoard: Map<Cell, Checker?>? = null
Для чего нужно это проперти?

2022-05-12 14:01 UTC, AbdullinAM commented on src/main/kotlin/core/Checker.kt
> +    private var mainBoard: Board? = null
Вообще вам нужно отказываться от привычки делать все подряд nullable. Надо наоборот стремиться к тому чтобы в коде было как можно меньше nullable переменных

2022-05-12 15:28 UTC, MikleAKA commented on src/main/kotlin/core/Board.kt
> +    private val checkers: MutableMap<Cell, Checker?> = mutableMapOf()
У chooseCell значение null , потому что это клетка , которая в данный момент выбрана , если клетка null , значит в данный момент игрок не выбрал шашку , которой будет ходить , то есть при клике на шашку , которой будет выполнен ход , chooseCell станет значением этой клетки , если есть необходимость съесть еще раз после съедения , тогда chooseCell примет значение клетки , на которой стоит шашка после съедения

В мапе потому что может быть Checker(Queen) - шашка(Королева) , может быть null - пустая клетка

2022-05-12 20:07 UTC, MikleAKA commented on src/main/kotlin/core/Checker.kt
> +    private var mainBoard: Board? = null
Если кинуть в конструктор , тогда будут проблемы с подклассом Queen

2022-05-19 22:42 UTC, MikleAKA commented on src/main/kotlin/tornadofx/CheckersApp.kt
> +package tornadofx
Исправлено

2022-05-19 22:42 UTC, MikleAKA commented on src/main/kotlin/core/Cell.kt
> +class Cell(val x: Int, val y: Int) {
Исправлено

2022-05-19 22:50 UTC, MikleAKA commented on src/main/kotlin/core/Checker.kt
> +    private var tempBoard: Map<Cell, Checker?>? = null
Исправлено

2022-05-30 08:27 UTC, AbdullinAM commented on src/main/kotlin/core/Board.kt
> +    private val checkers: MutableMap<Cell, Checker?> = mutableMapOf()
А почему у вас в мапе может быть null в качестве значения? Это само по себе неправильно

2022-05-30 08:27 UTC, AbdullinAM commented on src/main/kotlin/core/Checker.kt
> +    private var mainBoard: Board? = null
А какие будут проблемы?

2022-05-30 09:32 UTC, AbdullinAM commented on src/main/kotlin/tornadofx/CheckersView.kt
> +    private fun getPng(cell: Cell) = when {
Не знаю работает ли это у вас, но у меня из всех ваших картинок нормально отображается только whiteCell, т.к. он использует 8 бит на пиксель. А Все остальные картинки используют 24 бита на пиксель и не отображаются. 
Возможно это системно-зависимая штука, но проверьте еще раз. У меня нормально все работало только с 8 и с 32 битами на пиксель

2022-05-30 09:48 UTC, MikleAKA commented on src/main/kotlin/tornadofx/CheckersView.kt
> +    private fun getPng(cell: Cell) = when {
![chekers](https://user-images.githubusercontent.com/90031620/170966365-4919fc4d-07d7-4037-981a-2e01d7808d22.jpg)

2022-05-30 09:49 UTC, MikleAKA commented on src/main/kotlin/tornadofx/CheckersView.kt
> +    private fun getPng(cell: Cell) = when {
![image](https://user-images.githubusercontent.com/90031620/170966512-ffc4f4c5-12ae-4485-9256-d3d652a58183.png)

2022-05-30 16:35 UTC, MikleAKA commented on src/main/kotlin/core/Board.kt
> +    private val checkers: MutableMap<Cell, Checker?> = mutableMapOf()
исправлено

2022-05-31 11:44 UTC, MikleAKA commented on src/main/kotlin/core/Checker.kt
> +    private var mainBoard: Board? = null
исправлено

2022-06-02 13:46 UTC, AbdullinAM commented
Зачтено с оценкой 4.5

2022-06-02 13:46 UTC, closed without merging